# Data Cleaning and Preparation

## Library and Data Imports

In [48]:
import pandas as pd
import numpy as np 
import ast
import string
from spellchecker import SpellChecker
import json

from nltk.stem import PorterStemmer
from IPython.display import display


stemmer = PorterStemmer()

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [49]:
clean_df = pd.read_excel('Data/Inbound/cleaned_terms_updated.xlsx', sheet_name = 'Cleaned Terms')
remove_df = pd.read_excel('Data/Inbound/cleaned_terms_updated.xlsx', sheet_name = 'Removed Terms')

survey_df = pd.read_csv('Data/Inbound/final_data_export.csv')

In [50]:
print(f'Cleaned Terms: {clean_df.shape[0]} rows')
print(f'Removed Terms: {remove_df.shape[0]} rows')
print(f'Survey Data: {survey_df.shape[0]} rows, {survey_df.shape[1]} columns')

Cleaned Terms: 1345 rows
Removed Terms: 177 rows
Survey Data: 203 rows, 153 columns

## Survey Data Preparation

In [51]:
survey_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_10,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q3_8,Q3_9,Q3_10,Q4,Q5#1_1,Q5#1_2,Q5#1_3,Q5#1_4,Q5#1_5,Q5#1_6,Q5#1_7,Q5#1_8,Q5#1_9,Q5#1_10,Q5#1_11,Q5#2_1_1,Q5#2_2_1,Q5#2_3_1,Q5#2_4_1,Q5#2_5_1,Q5#2_6_1,Q5#2_7_1,Q5#2_8_1,Q5#2_9_1,Q5#2_10_1,Q5#2_11_1,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,Q6_10,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q7_7,Q7_8,Q7_9,Q7_10,Q8,Q9#1_1,Q9#1_2,Q9#1_3,Q9#1_4,Q9#1_5,Q9#1_6,Q9#1_7,Q9#1_8,Q9#1_9,Q9#1_10,Q9#1_11,Q9#2_1_1,Q9#2_2_1,Q9#2_3_1,Q9#2_4_1,Q9#2_5_1,Q9#2_6_1,Q9#2_7_1,Q9#2_8_1,Q9#2_9_1,Q9#2_10_1,Q9#2_11_1,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_10,Q11_1,Q11_2,Q11_3,Q11_4,Q11_5,Q11_6,Q11_7,Q11_8,Q11_9,Q11_10,Q12,Q13#1_1,Q13#1_2,Q13#1_3,Q13#1_4,Q13#1_5,Q13#1_6,Q13#1_7,Q13#1_8,Q13#1_9,Q13#1_10,Q13#1_11,Q13#2_1_1,Q13#2_2_1,Q13#2_3_1,Q13#2_4_1,Q13#2_5_1,Q13#2_6_1,Q13#2_7_1,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,"Statement of Consent\nI have read this form, b...",Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,"Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...",Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please tell us about yourself. What is your age?,How do you identify your gender? - Selected Ch...,How do you identify your gender? - Prefer to s...,Do you have an occupation related to video games?,What is your job? - Selected Choice,What is your job? - None of the above. My job ...
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}","{""ImportId"":""recipientFirstName""}","{""ImportId"":""recipientEmail""}","{""ImportId"":""externalDataReference""}","{""ImportId"":""locationLatitude""}","{""ImportId"":""locationLongitude""}","{""ImportId"":""distributionChannel""}","{""ImportId"":""userLanguage""}","{""ImportId"":""QID2""}","{""ImportId"":""QID3_1""}","{""ImportId"":""QID3_2""}","{""ImportId"":""QID3_3""}","{""ImportId"":""QID3_4""}","{""ImportId"":""QID3_5""}","{""ImportId"":""QID3_6""}","{""ImportId"":""QID3_7""}","{""ImportId"":""QID3_8""}","{""ImportId"":""QID3_9""}","{""ImportId"":""QID3_10""}","{""ImportId"":""QID4_x1""}","{""ImportId"":""QID4_x2""}","{""ImportId"":""QID4_x3""}","{""ImportId"":""QID4_x4""}","{""ImportId"":""QID4_x5""}","{""ImportId"":""QID4_x6""}","{""ImportId"":""QID4_x7""}","{""ImportId"":""QID4_x8""}","{""ImportId"":""QID4_x9""}","{""ImportId"":""QID4_x10""}","{""ImportId"":""QID6""}","{""ImportId"":""QID7#1_x1""}","{""ImportId"":""QID7#1_xx1""}","{""ImportId"":""QID7#1_xx2""}","{""ImportId"":""QID7#1_xx3""}","{""ImportId"":""QID7#1_xx4""}","{""ImportId"":""QID7#1_xx5""}","{""ImportId"":""QID7#1_xx6""}","{""ImportId"":""QID7#1_xx7""}","{""ImportId"":""QID7#1_xx8""}","{""ImportId"":""QID7#1_xx9""}","{""ImportId"":""QID7#1_xx10""}","{""ImportId"":""QID7#2_x1_1""}","{""ImportId"":""QID7#2_xx1_1""}","{""ImportId"":""QID7#2_xx2_1""}","{""ImportId"":""QID7#2_xx3_1""}","{""ImportId"":""QID7#2_xx4_1""}","{""ImportId"":""QID7#2_xx5_1""}","{""ImportId"":""QID7#2_xx6_1""}","{""ImportId"":""QID7#2_xx7_1""}","{""ImportId"":""QID7#2_xx8_1""}","{""ImportId"":""QID7#2_xx9_1""}","{""ImportId"":""QID7#2_xx10_1""}","{""ImportId"":""QID8_1""}","{""ImportId"":""QID8_2""}","{""ImportId"":""QID8_3""}","{""ImportId"":""QID8_4""}","{""ImportId"":""QID8_5""}","{""ImportId"":""QID8_6""}","{""ImportId"":""QID8_7""}","{""ImportId"":""QID8_8""}","{""ImportId"":""QID8_9""}","{""ImportId"":""QID8_10""}","{""ImportId"":""QID9_x1""}","{""ImportId"":""QID9_x2""}","{""ImportId"":""QID9_x3""}","{""ImportId"":""QID9_x4""}","{""ImportId"":""QID9_x5""}","{""ImportId"":""QID9_x6""}","{""ImportId"":""QID9_x7""}","{""ImportId"":""QID9_x8""}","{""ImportId"":""QID9_x9""}","{""ImportId"":""QID9_x10""}","{""ImportId"":""QID11""}","{""ImportId"":""QID12#1_x1""}","{""ImportId"":""QID12#1_xx1""}","{""ImportId"":""QID12#1_xx2""}","{""ImportId"":""QID12#1_xx3""}","{""ImportId"":""QID12#1_xx4""}","{""ImportId"":""QID12#1_xx5""}","{""ImportId"":""QID12#1_xx6""}","{""ImportId"":""QID12#1_xx7""}","{""ImportId"":""QID12#1_xx8""}","{""ImportId"":""QID12#1_xx9""}","{""ImportId"":""QID12#1_xx10""}","{""ImportId"":""QID12#2_x1_1""}","{""ImportId"":""QID12#2_xx1_1""}","{""ImportId"":""QID12#2_xx2_1""}","{""ImportId"":""QID12#2_xx3_1""}","{""ImportId"":""QID12#2_xx4_1""}","{""ImportId"":""QID12#2_xx5_1""}","{""ImportId"":""QID12#2_xx6_1""}","{""ImportId"":""QID12#2_xx7_1""}","{""ImportId"":""QID12#2_xx8_1""}","{""ImportId"":""QID12#2_xx9_1""}","{""ImportId"":""QID12#2_xx10_1""}","{""ImportId"":""QID13_1""}","{""ImportId"":""QID13_2""}","{""ImportId"":""QID13_3""}","{""ImportId"":""QID13_4""}","{""ImportId"":""QID13_5""}","{""ImportId"":""QID13_6""}","{""ImportId"":""QID13_7""}","{""ImportId"":""QID13_8""}","{""ImportId"":""QID13_9""}","{""ImportId"":""QID13_10""}","{""ImportId"":""QID14_x1""}","{""ImportId"":""QID14_x2""}","{""ImportId"":""QID14_x3""}","{""ImportId"":""QID14_x4""}","{""ImportId"":""QID14_x5""}","{""ImportId"":""QID14_x6""}","{""ImportId"":""QID14_x7""}","{""ImportId"":""QID14_x8""}","{""ImportId"":""QID14_x9""}","{""ImportId"":""QID14_x10""}","{""ImportId"":""QID16""}","{""ImportId"":""QID17#1_x1""}","{""ImportId"":""QID17#1_xx1""}","{""ImportId"":""QID17#1_xx2""}","{""ImportId"":""QID17#1_xx3""}","{""ImportId"":""QID17#1_xx4""}","{""ImportId"":""QID17#1_xx5""}","{""ImportId"":""QID17#1_xx6""}","{""ImportId"":""QID17#1_xx7""}","{""ImportId"":""QID17#1_xx8""}","{""ImportId"":""QID17#1_xx9""}","{""ImportId"":""QID17#1_xx10""}","{""ImportId"":""QID17#2_x1_1""}","{""ImportId"":""QID17#2_xx1_1""}","{""ImportId"":""QID17#2_xx2_1""}","{""ImportId"":""QID17#2_xx3_1""}","{""ImportId"":""QID17#2_xx4_1""}","{""ImportId"":""QID17#2_xx5_1""}","{""ImportId"":""QID17#2_xx6_1""}","{""ImportId"":""QID17#2_xx7_1""}","{""ImportId"":""QID17#2_xx8_1""}","{""ImportId"":""QID17#2_xx9_1""}","{""ImportId"":""QID17#2_xx10_1""}","{""ImportId"":""QID18""}","{""ImportId"":""QID19""}","{""ImportId"":""QID19_4_TEXT""}","{""ImportId"":""QID20""}","{""ImportId"":""QID21""}","{""ImportId"":""QID21_5_TEXT""}"
2,2025-04-30 11:21:17,2025-04-30 11:41:55,IP Address,184.58.198.91,100,1238,True,2025-04-30 11:41:56,R_1M0P04gYkqgIfoB,NaN,NaN,NaN,NaN,43.0818,-87.892,anonymous,EN,"I agree to participate, and I am 18 years or o...",Cozy,Peaceful,Homey,Nostalgic,Tranquil,Comforting,Harvesty,Intense,Hopeless,Chaotic,Peaceful,Peaceful,Light-hearted,Peaceful,Peaceful,Peaceful,No match,Intense,Dark,Dark,"Mood Term 4,Mood Term 10",NaN,NaN,NaN,NaN,"Light-hearted,Peaceful",NaN,NaN,NaN,NaN,NaN,"Dark,Intense",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cozy,Cute,Simple,Warm,Peaceful,Nostalgic,Satisfied,Fulfilled,Connected,Immersive,Peaceful,Cute,Light-hearted,Peaceful,Peaceful,Peaceful,No match,No match,No match,No match,Mood Term 6,NaN,NaN,NaN,NaN,NaN,NaN,"Light-hearted,Peaceful",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Intense,Anxious,Frustrated,Tormented,Tense,Haunting,Stressful,Overwhelming,Violent,Sextual,Intense,Intense,Intense,Horror,Intense,Horror,Intense,Intense,Dark,Sensual,"Mood Term 4,Mood Term 9",NaN,NaN,NaN,NaN,"Dark,Horror,Intense",NaN,NaN,NaN,NaN,"Dark,Horror,Intense",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-33,Female,NaN,No,NaN,NaN

In [52]:
question_df = survey_df[survey_df['StartDate'] == 'Start Date']
question_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_10,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q3_8,Q3_9,Q3_10,Q4,Q5#1_1,Q5#1_2,Q5#1_3,Q5#1_4,Q5#1_5,Q5#1_6,Q5#1_7,Q5#1_8,Q5#1_9,Q5#1_10,Q5#1_11,Q5#2_1_1,Q5#2_2_1,Q5#2_3_1,Q5#2_4_1,Q5#2_5_1,Q5#2_6_1,Q5#2_7_1,Q5#2_8_1,Q5#2_9_1,Q5#2_10_1,Q5#2_11_1,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,Q6_10,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q7_7,Q7_8,Q7_9,Q7_10,Q8,Q9#1_1,Q9#1_2,Q9#1_3,Q9#1_4,Q9#1_5,Q9#1_6,Q9#1_7,Q9#1_8,Q9#1_9,Q9#1_10,Q9#1_11,Q9#2_1_1,Q9#2_2_1,Q9#2_3_1,Q9#2_4_1,Q9#2_5_1,Q9#2_6_1,Q9#2_7_1,Q9#2_8_1,Q9#2_9_1,Q9#2_10_1,Q9#2_11_1,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_10,Q11_1,Q11_2,Q11_3,Q11_4,Q11_5,Q11_6,Q11_7,Q11_8,Q11_9,Q11_10,Q12,Q13#1_1,Q13#1_2,Q13#1_3,Q13#1_4,Q13#1_5,Q13#1_6,Q13#1_7,Q13#1_8,Q13#1_9,Q13#1_10,Q13#1_11,Q13#2_1_1,Q13#2_2_1,Q13#2_3_1,Q13#2_4_1,Q13#2_5_1,Q13#2_6_1,Q13#2_7_1,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,"Statement of Consent\nI have read this form, b...",Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Reflecting on the most recent video game you p...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,"Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...","Reflecting on your favorite video game, please...",Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,What type(s) of mood do you want to avoid in a...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Please categorize your mood terms. For each te...,Do any of your mood terms fit into multiple ca...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please tell us about yourself. What is your age?,How do you identify your gender? - Selected Ch...,How do you identify your gender? - Prefer to s...,Do you have an occupation related to video games?,What is your job? - Selected Choice,What is your job? - None of the above. My job ...

In [53]:
response_df = survey_df[(survey_df['StartDate']!= 'Start Date') & (survey_df['Status']!= '{"ImportId":"status"}')].reset_index(drop=True)
response_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_10,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q3_8,Q3_9,Q3_10,Q4,Q5#1_1,Q5#1_2,Q5#1_3,Q5#1_4,Q5#1_5,Q5#1_6,Q5#1_7,Q5#1_8,Q5#1_9,Q5#1_10,Q5#1_11,Q5#2_1_1,Q5#2_2_1,Q5#2_3_1,Q5#2_4_1,Q5#2_5_1,Q5#2_6_1,Q5#2_7_1,Q5#2_8_1,Q5#2_9_1,Q5#2_10_1,Q5#2_11_1,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,Q6_10,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q7_7,Q7_8,Q7_9,Q7_10,Q8,Q9#1_1,Q9#1_2,Q9#1_3,Q9#1_4,Q9#1_5,Q9#1_6,Q9#1_7,Q9#1_8,Q9#1_9,Q9#1_10,Q9#1_11,Q9#2_1_1,Q9#2_2_1,Q9#2_3_1,Q9#2_4_1,Q9#2_5_1,Q9#2_6_1,Q9#2_7_1,Q9#2_8_1,Q9#2_9_1,Q9#2_10_1,Q9#2_11_1,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_10,Q11_1,Q11_2,Q11_3,Q11_4,Q11_5,Q11_6,Q11_7,Q11_8,Q11_9,Q11_10,Q12,Q13#1_1,Q13#1_2,Q13#1_3,Q13#1_4,Q13#1_5,Q13#1_6,Q13#1_7,Q13#1_8,Q13#1_9,Q13#1_10,Q13#1_11,Q13#2_1_1,Q13#2_2_1,Q13#2_3_1,Q13#2_4_1,Q13#2_5_1,Q13#2_6_1,Q13#2_7_1,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,2025-04-30 11:21:17,2025-04-30 11:41:55,IP Address,184.58.198.91,100,1238,True,2025-04-30 11:41:56,R_1M0P04gYkqgIfoB,NaN,NaN,NaN,NaN,43.0818,-87.892,anonymous,EN,"I agree to participate, and I am 18 years or o...",Cozy,Peaceful,Homey,Nostalgic,Tranquil,Comforting,Harvesty,Intense,Hopeless,Chaotic,Peaceful,Peaceful,Light-hearted,Peaceful,Peaceful,Peaceful,No match,Intense,Dark,Dark,"Mood Term 4,Mood Term 10",NaN,NaN,NaN,NaN,"Light-hearted,Peaceful",NaN,NaN,NaN,NaN,NaN,"Dark,Intense",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cozy,Cute,Simple,Warm,Peaceful,Nostalgic,Satisfied,Fulfilled,Connected,Immersive,Peaceful,Cute,Light-hearted,Peaceful,Peaceful,Peaceful,No match,No match,No match,No match,Mood Term 6,NaN,NaN,NaN,NaN,NaN,NaN,"Light-hearted,Peaceful",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Intense,Anxious,Frustrated,Tormented,Tense,Haunting,Stressful,Overwhelming,Violent,Sextual,Intense,Intense,Intense,Horror,Intense,Horror,Intense,Intense,Dark,Sensual,"Mood Term 4,Mood Term 9",NaN,NaN,NaN,NaN,"Dark,Horror,Intense",NaN,NaN,NaN,NaN,"Dark,Horror,Intense",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-33,Female,NaN,No,NaN,NaN
1,2025-04-30 12:34:03,2025-04-30 12:39:20,IP Address,68.55.41.237,100,317,True,2025-04-30 12:39:21,R_6hA6yOKSGzPDXlp,NaN,NaN,NaN,NaN,42.3757,-85.4447,anonymous,EN,"I agree to participate, and I am 18 years or o...",Solemn,Cerebral,Calm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peaceful,Imaginative,Peaceful,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Calm,Cerebral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peaceful,Imaginative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Depressing,Frustrating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sad,Mysterious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50-57,Male,NaN,No,NaN,NaN
2,2025-04-30 14:30:54,2025-04-30 14:39:56,IP Address,184.58.199.136,100,541,True,2025-04-30 14:39:57,R_34jUAPsFHDjPeyy,NaN,NaN,NaN,NaN,43.0818,-87.892,anonymous,EN,"I agree to participate, and I am 18 years or o...",relaxing,engrossing,makes-you-think,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Peaceful,No match,Imaginative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,creative,fun,relaxing,imaginative,explorative,NaN,NaN,NaN,NaN,NaN,Imaginative,Light-hearted,Peaceful,Imaginative,Adventurous,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,depressing,sad,gross,horror,NaN,NaN,NaN,NaN,NaN,NaN,Sad,Sad,Dark,Horror,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50-57,Female,NaN,No,NaN,NaN

In [54]:
response_df.shape

(201, 153)

## Date Filtering

In [55]:
#Make date column

response_df['StartDateDTM'] = pd.to_datetime(response_df['StartDate'])
response_df['EndDateDTM'] = pd.to_datetime(response_df['EndDate'])  
response_df[['StartDateDTM', 'EndDateDTM']].head(3)

         StartDateDTM          EndDateDTM
0 2025-04-30 11:21:17 2025-04-30 11:41:55
1 2025-04-30 12:34:03 2025-04-30 12:39:20
2 2025-04-30 14:30:54 2025-04-30 14:39:56

In [56]:
response_df['StartDateYear'] = response_df['StartDateDTM'].dt.year
response_df['StartDateMonth'] = response_df['StartDateDTM'].dt.month
response_df['StartDateDay'] = response_df['StartDateDTM'].dt.day

response_df.groupby(by=['StartDateYear', 'StartDateMonth']).size()

StartDateYear  StartDateMonth
2025           4                  16
               5                 174
               6                   9
               9                   2
dtype: int64

In [57]:
response_df = response_df[response_df['StartDateDTM']<= '2025-06-01'].reset_index(drop=True)
response_df.shape

(190, 158)

## Completion Filtering

In [58]:
response_df.groupby(by='Progress').size()

Progress
10     58
100    81
14     10
24      3
29      7
33     25
57      6
dtype: int64

In [59]:
response_df[response_df['Progress'] == '57'].head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q1,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_10,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q3_8,Q3_9,Q3_10,Q4,Q5#1_1,Q5#1_2,Q5#1_3,Q5#1_4,Q5#1_5,Q5#1_6,Q5#1_7,Q5#1_8,Q5#1_9,Q5#1_10,Q5#1_11,Q5#2_1_1,Q5#2_2_1,Q5#2_3_1,Q5#2_4_1,Q5#2_5_1,Q5#2_6_1,Q5#2_7_1,Q5#2_8_1,Q5#2_9_1,Q5#2_10_1,Q5#2_11_1,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,Q6_10,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q7_7,Q7_8,Q7_9,Q7_10,Q8,Q9#1_1,Q9#1_2,Q9#1_3,Q9#1_4,Q9#1_5,Q9#1_6,Q9#1_7,Q9#1_8,Q9#1_9,Q9#1_10,Q9#1_11,Q9#2_1_1,Q9#2_2_1,Q9#2_3_1,Q9#2_4_1,Q9#2_5_1,Q9#2_6_1,Q9#2_7_1,Q9#2_8_1,Q9#2_9_1,Q9#2_10_1,Q9#2_11_1,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_10,Q11_1,Q11_2,Q11_3,Q11_4,Q11_5,Q11_6,Q11_7,Q11_8,Q11_9,Q11_10,Q12,Q13#1_1,Q13#1_2,Q13#1_3,Q13#1_4,Q13#1_5,Q13#1_6,Q13#1_7,Q13#1_8,Q13#1_9,Q13#1_10,Q13#1_11,Q13#2_1_1,Q13#2_2_1,Q13#2_3_1,Q13#2_4_1,Q13#2_5_1,Q13#2_6_1,Q13#2_7_1,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT,StartDateDTM,EndDateDTM,StartDateYear,StartDateMonth,StartDateDay
61,2025-05-03 11:34:57,2025-05-03 11:37:09,IP Address,174.107.174.35,57,131,False,2025-05-10 11:37:11,R_3f2XjICEuVgBCIp,NaN,NaN,NaN,NaN,34.1847,-79.7704,anonymous,EN,"I agree to participate, and I am 18 years or o...",Heartwrenching,Atmospheric,Compelling,Mysterious,Foreboding,NaN,NaN,NaN,NaN,NaN,Sad,Imaginative,Sensual,Mysterious,Solitary,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-03 11:34:57,2025-05-03 11:37:09,2025,5,3
88,2025-05-08 15:25:42,2025-05-08 15:35:36,IP Address,174.192.135.228,57,593,False,2025-05-15 15:35:40,R_3efVRrUqZC5yRyO,NaN,NaN,NaN,NaN,42.3667,-88.0925,anonymous,EN,"I agree to participate, and I am 18 years or o...",Dark,Comedic,Silly,Heartbreaking,Thrilling,Suspenseful,Confusing,Abstract,NaN,NaN,Dark,Humorous,Quirky,Sad,Intense,Mysterious,Quirky,Quirky,NaN,NaN,"Mood Term 3,Mood Term 4,Mood Term 7,Mood Term 8",NaN,NaN,NaN,"Cute,Imaginative,Quirky","Intense,Romantic,Sensual,Solitary",NaN,NaN,"Adventurous,Imaginative","Adventurous,Imaginative,Quirky,Sensual",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dark,Satirical,Silly,Suspenseful,Stressful,NaN,NaN,NaN,NaN,NaN,Dark,Sarcastic,Humorous,Intense,Intense,NaN,NaN,NaN,NaN,NaN,"Mood Term 3,Mood Term 4,Mood Term 5",NaN,NaN,NaN,"Cute,Imaginative,Light-hearted,Quirky","Adventurous,Aggressive,Intense,Mysterious","Aggressive,Intense",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-08 15:25:42,2025-05-08 15:35:36,2025,5,8
146,2025-05-16 17:37:43,2025-05-16 18:11:52,IP Address,67.87.104.250,57,2048,False,2025-05-23 18:11:55,R_7GFJ9PMlDQfyRWh,NaN,NaN,NaN,NaN,40.8566,-74.8389,anonymous,EN,"I agree to participate, and I am 18 years or o...",Terrifying,Adventure,Exciting,Amusing,Thought-provoking,Violent,Happy,Captivating,Idyllic,Bitterness,Horror,Adventurous,Adventurous,Humorous,Intense,Aggressive,Light-hearted,Intense,Cute,Sad,"Mood Term 3,Mood Term 5,Mood Term 8,Mood Term 10",NaN,NaN,NaN,"Adventurous,Imaginative,Intense,Mysterious",NaN,"Adventurous,Dark,Imaginative,Intense,Mysteriou...",NaN,NaN,"Adventurous,Aggressive,Dark,Imaginative,Intens...",NaN,"Aggressive,Dark,Intense,Mysterious,Sad",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grim,Violent,Thought-provoking,Humorous,Sad,Heart-breaking,Scary,Adventurous,Mysterious,Happy,Dark,Aggressive,Intense,Humorous,Sad,Sad,Horror,Adventurous,Mysterious,Light-hearted,"Mood Term 1,Mood Term 3,Mood Term 6,Mood Term 10",NaN,"Aggressive,Dark,Horror,Intense,Sad",NaN,"Adventurous,Imaginative,Intense,Mysterious",NaN,NaN,"Dark,Intense,Sad",NaN,NaN,NaN,"Adventurous,Cute,Humorous,Light-hearted,Peacef...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-05-16 17:37:43,2025-05-16 18:11:52,2025,5,16

In [60]:
response_df['Progress'] = pd.to_numeric(response_df['Progress'])
response_df = response_df[response_df['Progress'] >= 33].reset_index(drop=True)
response_df.shape

(112, 158)

# Explode Survey Records

In [61]:
response_df.columns.to_list()

['StartDate',
 'EndDate',
 'Status',
 'IPAddress',
 'Progress',
 'Duration (in seconds)',
 'Finished',
 'RecordedDate',
 'ResponseId',
 'RecipientLastName',
 'RecipientFirstName',
 'RecipientEmail',
 'ExternalReference',
 'LocationLatitude',
 'LocationLongitude',
 'DistributionChannel',
 'UserLanguage',
 'Q1',
 'Q2_1',
 'Q2_2',
 'Q2_3',
 'Q2_4',
 'Q2_5',
 'Q2_6',
 'Q2_7',
 'Q2_8',
 'Q2_9',
 'Q2_10',
 'Q3_1',
 'Q3_2',
 'Q3_3',
 'Q3_4',
 'Q3_5',
 'Q3_6',
 'Q3_7',
 'Q3_8',
 'Q3_9',
 'Q3_10',
 'Q4',
 'Q5#1_1',
 'Q5#1_2',
 'Q5#1_3',
 'Q5#1_4',
 'Q5#1_5',
 'Q5#1_6',
 'Q5#1_7',
 'Q5#1_8',
 'Q5#1_9',
 'Q5#1_10',
 'Q5#1_11',
 'Q5#2_1_1',
 'Q5#2_2_1',
 'Q5#2_3_1',
 'Q5#2_4_1',
 'Q5#2_5_1',
 'Q5#2_6_1',
 'Q5#2_7_1',
 'Q5#2_8_1',
 'Q5#2_9_1',
 'Q5#2_10_1',
 'Q5#2_11_1',
 'Q6_1',
 'Q6_2',
 'Q6_3',
 'Q6_4',
 'Q6_5',
 'Q6_6',
 'Q6_7',
 'Q6_8',
 'Q6_9',
 'Q6_10',
 'Q7_1',
 'Q7_2',
 'Q7_3',
 'Q7_4',
 'Q7_5',
 'Q7_6',
 'Q7_7',
 'Q7_8',
 'Q7_9',
 'Q7_10',
 'Q8',
 'Q9#1_1',
 'Q9#1_2',
 'Q9#1_3',
 'Q9#1_4',
 'Q9#1_5',
 'Q9#1_6',
 'Q9#1_7',
 'Q9#1_8',
 'Q9#1_9',
 'Q9#1_10',
 'Q9#1_11',
 'Q9#2_1_1',
 'Q9#2_2_1',
 'Q9#2_3_1',
 'Q9#2_4_1',
 'Q9#2_5_1',
 'Q9#2_6_1',
 'Q9#2_7_1',
 'Q9#2_8_1',
 'Q9#2_9_1',
 'Q9#2_10_1',
 'Q9#2_11_1',
 'Q10_1',
 'Q10_2',
 'Q10_3',
 'Q10_4',
 'Q10_5',
 'Q10_6',
 'Q10_7',
 'Q10_8',
 'Q10_9',
 'Q10_10',
 'Q11_1',
 'Q11_2',
 'Q11_3',
 'Q11_4',
 'Q11_5',
 'Q11_6',
 'Q11_7',
 'Q11_8',
 'Q11_9',
 'Q11_10',
 'Q12',
 'Q13#1_1',
 'Q13#1_2',
 'Q13#1_3',
 'Q13#1_4',
 'Q13#1_5',
 'Q13#1_6',
 'Q13#1_7',
 'Q13#1_8',
 'Q13#1_9',
 'Q13#1_10',
 'Q13#1_11',
 'Q13#2_1_1',
 'Q13#2_2_1',
 'Q13#2_3_1',
 'Q13#2_4_1',
 'Q13#2_5_1',
 'Q13#2_6_1',
 'Q13#2_7_1',
 'Q13#2_8_1',
 'Q13#2_9_1',
 'Q13#2_10_1',
 'Q13#2_11_1',
 'Q14',
 'Q15',
 'Q15_4_TEXT',
 'Q16',
 'Q17',
 'Q17_5_TEXT',
 'StartDateDTM',
 'EndDateDTM',
 'StartDateYear',
 'StartDateMonth',
 'StartDateDay']

### Recent Mood

In [62]:
recent_q = ['Q2_1','Q2_2','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7','Q2_8','Q2_9','Q2_10']
recent_categories = ['Q3_1','Q3_2','Q3_3','Q3_4','Q3_5','Q3_6','Q3_7','Q3_8','Q3_9','Q3_10']

In [63]:
recent_q_terms = []
term_template = {
    'metadata.ResponseId': '',
    'metadata.Finished': '',
    'metadata.Progress': '',
    'metadata.TermTrack': '',
    'metadata.QuestionId': '',
    'QX_X.UserProvidedMoodTerm': '',
    'QX_X.CleanedMoodTerm': '',
    'QX_X.UserCategoryMapping': '',
    'QX.MultipleCategoryTerm': '',
    'QX#1_X.MultipleCategoryMapping': '',
    'QX#2_X_1.UserProvidedCategory': '',
    'QX#2_X_1.CleanedCategory': '',
}

In [64]:
for idx, row in response_df.iterrows():
    # if the progress < 33, skip the row. They have not completed all of the modules for recent game mood terms
    if row['Progress'] < 33:
        continue
    try:
        for id,q in enumerate(recent_q):
            if pd.isna(row[q]):
                continue
            else:
                json_obj = term_template.copy()
                json_obj['metadata.TermTrack'] = 'Recent'
                json_obj['metadata.ResponseId'] = row['ResponseId']
                json_obj['metadata.Finished'] = row['Finished']
                json_obj['metadata.Progress'] = row['Progress']
                json_obj['metadata.QuestionId'] = q
                question_id = q.split('_')[1]

                multiple_categories = row['Q4']
                if multiple_categories != 'No':
                    multiple_category_terms = multiple_categories.split(',')
                    multiple_category_terms = [cat.strip('Mood Term') for cat in multiple_category_terms]   
                else: 
                    multiple_category_terms = []    

                #check if the mood term is NaN
                
                json_obj['QX_X.UserProvidedMoodTerm'] = row[q]

                #clean the mood term
                #step 1 - remove leading hashtag
                mood_term = row[q].lstrip('#').strip()
                #step 2 - lowercase
                mood_term = mood_term.lower()
                #step 3 - spell check
                spell = SpellChecker()
                mood_term_cleaned = spell.correction(mood_term)

                if mood_term_cleaned != None:
                    json_obj['QX_X.CleanedMoodTerm'] = mood_term_cleaned
                else: json_obj['QX_X.CleanedMoodTerm'] = mood_term
                    
                #gather the user mapped category
                json_obj['QX_X.UserCategoryMapping'] = row[recent_categories[id]]

                #identify multiple categories
                if question_id in multiple_category_terms:
                    json_obj['QX.MultipleCategoryTerm'] = True

                    if pd.notna(row[f'Q5#1_{int(question_id)+1}']):
                        #split the multiple categories by comma
                        json_obj['QX#1_X.MultipleCategoryMapping'] = row[f'Q5#1_{int(question_id)+1}'].split(',')
                    else: 
                        json_obj['QX#1_X.MultipleCategoryMapping'] = None

                    if pd.notna(row[f'Q5#2_{int(question_id)+1}_1']):
                        json_obj['QX#2_X_1.UserProvidedCategory'] = row[f'Q5#2_{int(question_id)+1}_1']
                        #clean the category
                        user_provided_category = row[f'Q5#2_{int(question_id)+1}_1'].strip().lower()
                        user_provided_category_cleaned = spell.correction(user_provided_category)

                        if mood_term_cleaned != None:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category_cleaned
                        else:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category
                    else:
                        json_obj['QX#2_X_1.UserProvidedCategory'] = None
                        json_obj['QX#2_X_1.CleanedCategory'] = None

                else:
                    json_obj['QX.MultipleCategoryTerm'] = False
                    json_obj['QX#1_X.MultipleCategoryMapping'] = None
                    json_obj['QX#2_X_1.UserProvidedCategory'] = None
                    json_obj['QX#2_X_1.CleanedCategory'] = None

                recent_q_terms.append(json_obj)
    except Exception as e:
        print(f"Error processing row {idx}: {e}")
        break

In [65]:
# convert the array to a DataFrame and save to CSV
recent_q_df = pd.DataFrame(recent_q_terms)
recent_q_df.to_csv('Data/Outbound/recent_q_terms.csv', index=False, header=True)

In [66]:
recent_q_df.shape

(661, 12)

In [67]:
#test to ensure that all terms are captured
recent_terms_df = response_df[response_df['Progress'] >= 33][recent_q].copy()
total_recent_terms = pd.DataFrame(recent_terms_df[recent_q].count(axis=1))
total_recent_terms.rename(columns={0:'Total_Recent_Terms'}, inplace=True)
total_recent_terms.sum()

Total_Recent_Terms    661
dtype: int64

### Favorite Mood

In [68]:
fav_q = ['Q6_1','Q6_2','Q6_3','Q6_4','Q6_5','Q6_6','Q6_7','Q6_8','Q6_9','Q6_10']
fav_categories = ['Q7_1','Q7_2','Q7_3','Q7_4','Q7_5','Q7_6','Q7_7','Q7_8','Q7_9','Q7_10']

In [69]:
fav_q_terms = []
term_template = {
    'metadata.ResponseId': '',
    'metadata.Finished': '',
    'metadata.Progress': '',
    'metadata.TermTrack': '',
    'metadata.QuestionId': '',
    'QX_X.UserProvidedMoodTerm': '',
    'QX_X.CleanedMoodTerm': '',
    'QX_X.UserCategoryMapping': '',
    'QX.MultipleCategoryTerm': '',
    'QX#1_X.MultipleCategoryMapping': '',
    'QX#2_X_1.UserProvidedCategory': '',
    'QX#2_X_1.CleanedCategory': '',
}

In [70]:
for idx, row in response_df.iterrows():
    # if the progress < 57, skip the row. They have not completed all of the modules for fav game mood terms
    if row['Progress'] < 57:
        continue
    try:
        for id,q in enumerate(fav_q):
            if pd.isna(row[q]):
                continue
            else:
                json_obj = term_template.copy()
                json_obj['metadata.TermTrack'] = 'Favorite'
                json_obj['metadata.ResponseId'] = row['ResponseId']
                json_obj['metadata.Finished'] = row['Finished']
                json_obj['metadata.Progress'] = row['Progress']
                json_obj['metadata.QuestionId'] = q
                question_id = q.split('_')[1]

                multiple_categories = row['Q8']
                if multiple_categories != 'No':
                    multiple_category_terms = multiple_categories.split(',')
                    multiple_category_terms = [cat.strip('Mood Term') for cat in multiple_category_terms]   
                else: 
                    multiple_category_terms = []    

                #check if the mood term is NaN
                
                json_obj['QX_X.UserProvidedMoodTerm'] = row[q]

                #clean the mood term
                #step 1 - remove leading hashtag
                mood_term = row[q].lstrip('#').strip()
                #step 2 - lowercase
                mood_term = mood_term.lower()
                #step 3 - spell check
                spell = SpellChecker()
                mood_term_cleaned = spell.correction(mood_term)

                if mood_term_cleaned != None:
                    json_obj['QX_X.CleanedMoodTerm'] = mood_term_cleaned
                else: json_obj['QX_X.CleanedMoodTerm'] = mood_term
                    
                #gather the user mapped category
                json_obj['QX_X.UserCategoryMapping'] = row[fav_categories[id]]

                #identify multiple categories
                if question_id in multiple_category_terms:
                    json_obj['QX.MultipleCategoryTerm'] = True

                    if pd.notna(row[f'Q9#1_{int(question_id)+1}']):
                        #split the multiple categories by comma
                        json_obj['QX#1_X.MultipleCategoryMapping'] = row[f'Q9#1_{int(question_id)+1}'].split(',')
                    else: 
                        json_obj['QX#1_X.MultipleCategoryMapping'] = None

                    if pd.notna(row[f'Q9#2_{int(question_id)+1}_1']):
                        json_obj['QX#2_X_1.UserProvidedCategory'] = row[f'Q9#2_{int(question_id)+1}_1']
                        #clean the category
                        user_provided_category = row[f'Q9#2_{int(question_id)+1}_1'].strip().lower()
                        user_provided_category_cleaned = spell.correction(user_provided_category)

                        if mood_term_cleaned != None:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category_cleaned
                        else:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category
                    else:
                        json_obj['QX#2_X_1.UserProvidedCategory'] = None
                        json_obj['QX#2_X_1.CleanedCategory'] = None

                else:
                    json_obj['QX.MultipleCategoryTerm'] = False
                    json_obj['QX#1_X.MultipleCategoryMapping'] = None
                    json_obj['QX#2_X_1.UserProvidedCategory'] = None
                    json_obj['QX#2_X_1.CleanedCategory'] = None

                fav_q_terms.append(json_obj)
    except Exception as e:
        print(f"Error processing row {idx}: {e}")
        break

In [71]:
# convert the array to a DataFrame and save to CSV
fav_q_df = pd.DataFrame(fav_q_terms)
fav_q_df.to_csv('Data/Outbound/fav_q_terms.csv', index=False, header=True)

In [72]:
fav_q_df.shape

(514, 12)

In [73]:
#test to ensure that all terms are captured
fav_terms_df = response_df[response_df['Progress'] >= 57][fav_q].copy()
total_fav_terms = pd.DataFrame(fav_terms_df[fav_q].count(axis=1))
total_fav_terms.rename(columns={0:'Total_Favorite_Terms'}, inplace=True)
total_fav_terms.sum()

Total_Favorite_Terms    514
dtype: int64

### Avoid Mood

In [74]:
avoid_q = ['Q10_1','Q10_2','Q10_3','Q10_4','Q10_5','Q10_6','Q10_7','Q10_8','Q10_9','Q10_10']
avoid_categories = ['Q11_1','Q11_2','Q11_3','Q11_4','Q11_5','Q11_6','Q11_7','Q11_8','Q11_9','Q11_10']

In [75]:
avoid_q_terms = []
term_template = {
    'metadata.ResponseId': '',
    'metadata.Finished': '',
    'metadata.Progress': '',
    'metadata.TermTrack': '',
    'metadata.QuestionId': '',
    'QX_X.UserProvidedMoodTerm': '',
    'QX_X.CleanedMoodTerm': '',
    'QX_X.UserCategoryMapping': '',
    'QX.MultipleCategoryTerm': '',
    'QX#1_X.MultipleCategoryMapping': '',
    'QX#2_X_1.UserProvidedCategory': '',
    'QX#2_X_1.CleanedCategory': '',
}

In [76]:
for idx, row in response_df.iterrows():
    # if the progress < 100, skip the row. They have not completed all of the modules for fav game mood terms
    if row['Progress'] < 100:
        continue
    try:
        for id,q in enumerate(avoid_q):
            if pd.isna(row[q]):
                continue
            else:
                json_obj = term_template.copy()
                json_obj['metadata.TermTrack'] = 'Avoid'
                json_obj['metadata.ResponseId'] = row['ResponseId']
                json_obj['metadata.Finished'] = row['Finished']
                json_obj['metadata.Progress'] = row['Progress']
                json_obj['metadata.QuestionId'] = q
                question_id = q.split('_')[1]

                multiple_categories = row['Q12']
                if multiple_categories != 'No':
                    multiple_category_terms = multiple_categories.split(',')
                    multiple_category_terms = [cat.strip('Mood Term') for cat in multiple_category_terms]   
                else: 
                    multiple_category_terms = []    

                #check if the mood term is NaN
                
                json_obj['QX_X.UserProvidedMoodTerm'] = row[q]

                #clean the mood term
                #step 1 - remove leading hashtag
                mood_term = row[q].lstrip('#').strip()
                #step 2 - lowercase
                mood_term = mood_term.lower()
                #step 3 - spell check
                spell = SpellChecker()
                mood_term_cleaned = spell.correction(mood_term)

                if mood_term_cleaned != None:
                    json_obj['QX_X.CleanedMoodTerm'] = mood_term_cleaned
                else: json_obj['QX_X.CleanedMoodTerm'] = mood_term
                    
                #gather the user mapped category
                json_obj['QX_X.UserCategoryMapping'] = row[avoid_categories[id]]

                #identify multiple categories
                if question_id in multiple_category_terms:
                    json_obj['QX.MultipleCategoryTerm'] = True

                    if pd.notna(row[f'Q13#1_{int(question_id)+1}']):
                        #split the multiple categories by comma
                        json_obj['QX#1_X.MultipleCategoryMapping'] = row[f'Q13#1_{int(question_id)+1}'].split(',')
                    else: 
                        json_obj['QX#1_X.MultipleCategoryMapping'] = None

                    if pd.notna(row[f'Q13#2_{int(question_id)+1}_1']):
                        json_obj['QX#2_X_1.UserProvidedCategory'] = row[f'Q13#2_{int(question_id)+1}_1']
                        #clean the category
                        user_provided_category = row[f'Q13#2_{int(question_id)+1}_1'].strip().lower()
                        user_provided_category_cleaned = spell.correction(user_provided_category)

                        if mood_term_cleaned != None:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category_cleaned
                        else:
                            json_obj['QX#2_X_1.CleanedCategory'] = user_provided_category
                    else:
                        json_obj['QX#2_X_1.UserProvidedCategory'] = None
                        json_obj['QX#2_X_1.CleanedCategory'] = None

                else:
                    json_obj['QX.MultipleCategoryTerm'] = False
                    json_obj['QX#1_X.MultipleCategoryMapping'] = None
                    json_obj['QX#2_X_1.UserProvidedCategory'] = None
                    json_obj['QX#2_X_1.CleanedCategory'] = None

                avoid_q_terms.append(json_obj)
    except Exception as e:
        print(f"Error processing row {idx}: {e}")
        break

In [77]:
# convert the array to a DataFrame and save to CSV
avoid_q_df = pd.DataFrame(avoid_q_terms)
avoid_q_df.to_csv('Data/Outbound/avoid_q_terms.csv', index=False, header=True)

In [78]:
avoid_q_df.shape

(324, 12)

In [79]:
#test to ensure that all terms are captured
avoid_terms_df = response_df[response_df['Progress'] >= 100][avoid_q].copy()
total_avoid_terms = pd.DataFrame(avoid_terms_df[avoid_q].count(axis=1))
total_avoid_terms.rename(columns={0:'Total_Avoid_Terms'}, inplace=True)
total_avoid_terms.sum()

Total_Avoid_Terms    324
dtype: int64

In [80]:
term_df = pd.concat([recent_q_df, fav_q_df, avoid_q_df], ignore_index=True)
term_df.reset_index(drop=True, inplace=True)
term_df.to_csv('Data/Outbound/all_terms.csv', index=False, header=True)
term_df.to_excel('Data/Outbound/all_terms.xlsx', index=False, header=True)

In [81]:
term_df.shape

(1499, 12)

## Stemming

In [82]:
#duplicate the base dataframe to avoid modifying the original
temp_df = term_df.copy()
temp_df.insert(7, 'QX_X.CleanedTermStem', '', True)
temp_df.insert(8, 'QX_X.RemovedTermFlag', '', True)

# remove all whitespace from the term columns
temp_df['QX_X.UserProvidedMoodTerm'] = temp_df['QX_X.UserProvidedMoodTerm'].str.strip()
temp_df['QX_X.CleanedMoodTerm'] = temp_df['QX_X.CleanedMoodTerm'].str.strip()

In [83]:
temp_df.head(3)

,metadata.ResponseId,metadata.Finished,metadata.Progress,metadata.TermTrack,metadata.QuestionId,QX_X.UserProvidedMoodTerm,QX_X.CleanedMoodTerm,QX_X.CleanedTermStem,QX_X.RemovedTermFlag,QX_X.UserCategoryMapping,QX.MultipleCategoryTerm,QX#1_X.MultipleCategoryMapping,QX#2_X_1.UserProvidedCategory,QX#2_X_1.CleanedCategory
0,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_1,Cozy,cozy,,,Peaceful,False,None,None,None
1,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_2,Peaceful,peaceful,,,Peaceful,False,None,None,None
2,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_3,Homey,homey,,,Light-hearted,False,None,None,None

In [84]:
#duplicate the base dataframe to avoid modifying the original
clean_temp_df = clean_df.copy()

# remove all whitespace from the term columns
clean_temp_df['QX_X.UserProvidedMoodTerm'] = clean_temp_df['QX_X.UserProvidedMoodTerm'].str.strip()
clean_temp_df['QX_X.CleanedMoodTerm'] = clean_temp_df['QX_X.CleanedMoodTerm'].str.strip()

In [85]:
clean_temp_df.head(3)

,metadata.ResponseId,metadata.Finished,metadata.Progress,metadata.TermTrack,metadata.QuestionId,QX_X.UserProvidedMoodTerm,QX_X.CleanedMoodTerm,QX_X.CleanedTermStem,QX_X.UserCategoryMapping,QX.MultipleCategoryTerm,QX#1_X.MultipleCategoryMapping,QX#2_X_1.UserProvidedCategory,QX#2_X_1.CleanedCategory
0,R_1adu8XGo0BEYT2V,True,100,Recent,Q2_5,Baldurs Gate 3 - fulfilling,fulfilling,fulfil,Adventurous,True,"['Adventurous', 'Dark', 'Horror', 'Humorous']",NaN,NaN
1,R_1adu8XGo0BEYT2V,True,100,Avoid,Q10_2,Boredom,boring,bore,No match,False,NaN,NaN,NaN
2,R_1adu8XGo0BEYT2V,True,100,Recent,Q2_1,"Celeste - thrilling,",thrilling,thrill,Adventurous,True,"['Adventurous', 'Humorous', 'Intense', 'Sensual']",NaN,NaN

In [86]:
#duplicate the base dataframe to avoid modifying the original
remove_temp_df = remove_df.copy()

# remove all whitespace from the term columns
remove_temp_df['QX_X.UserProvidedMoodTerm'] = remove_temp_df['QX_X.UserProvidedMoodTerm'].str.strip()
remove_temp_df['QX_X.CleanedMoodTerm'] = remove_temp_df['QX_X.CleanedMoodTerm'].str.strip()

In [87]:
remove_temp_df.head(3)

,metadata.ResponseId,metadata.Finished,metadata.Progress,metadata.TermTrack,metadata.QuestionId,QX_X.UserProvidedMoodTerm,QX_X.CleanedMoodTerm,QX_X.UserCategoryMapping,QX.MultipleCategoryTerm,QX#1_X.MultipleCategoryMapping,QX#2_X_1.UserProvidedCategory,QX#2_X_1.CleanedCategory
0,R_7s8WZ7aK1AxrUYN,True,100,Recent,Q2_2,#Learning,learning,Adventurous,True,"['Adventurous', 'Imaginative', 'Intense']",NaN,NaN
1,R_7KqMe1mO2Pm9rBu,True,100,Avoid,Q10_5,#loud,loud,Aggressive,False,NaN,NaN,NaN
2,R_7s8WZ7aK1AxrUYN,True,100,Recent,Q2_4,#Mastery,mastery,Imaginative,True,"['Adventurous', 'Imaginative', 'Solitary']",NaN,NaN

In [88]:
for idx, row in temp_df.iterrows():
    user_provided_mood_term = row['QX_X.UserProvidedMoodTerm']
    cleaned_mood_term = row['QX_X.CleanedMoodTerm']

    #removed term check
    if user_provided_mood_term in remove_temp_df['QX_X.UserProvidedMoodTerm'].values or cleaned_mood_term in remove_temp_df['QX_X.CleanedMoodTerm'].values:

        #update values
        temp_df.at[idx, 'QX_X.RemovedTermFlag'] = True
        temp_df.at[idx, 'QX_X.CleanedMoodTerm'] = remove_temp_df.loc[
            remove_temp_df['QX_X.UserProvidedMoodTerm'] == user_provided_mood_term,
            'QX_X.CleanedMoodTerm'
        ].iloc[0]

        #stem the cleaned mood term
        stemmed_term = stemmer.stem(temp_df.at[idx, 'QX_X.CleanedMoodTerm'])
        temp_df.at[idx, 'QX_X.CleanedTermStem'] = stemmed_term

        #print results
        print(f"REMOVED Term Found: '{user_provided_mood_term}' mapped to Cleaned Term: '{temp_df.at[idx, 'QX_X.CleanedMoodTerm']}' with Stem: '{stemmed_term}'")
    elif user_provided_mood_term not in remove_temp_df['QX_X.UserProvidedMoodTerm'].values and cleaned_mood_term not in remove_temp_df['QX_X.CleanedMoodTerm'].values:

        #update values
        temp_df.at[idx, 'QX_X.RemovedTermFlag'] = False
        temp_df.at[idx, 'QX_X.CleanedMoodTerm'] = clean_temp_df.loc[
            clean_temp_df['QX_X.UserProvidedMoodTerm'] == user_provided_mood_term, 'QX_X.CleanedMoodTerm'].iloc[0]

        #stem the cleaned mood term
        stemmed_term = stemmer.stem(temp_df.at[idx, 'QX_X.CleanedMoodTerm'])
        temp_df.at[idx, 'QX_X.CleanedTermStem'] = stemmed_term

        #print results
        print(f"KEEP TERM: '{user_provided_mood_term}' with Cleaned Term: '{cleaned_mood_term}' and Stem: '{stemmed_term}'")

KEEP TERM: 'Cozy' with Cleaned Term: 'cozy' and Stem: 'cozi'
KEEP TERM: 'Peaceful' with Cleaned Term: 'peaceful' and Stem: 'peac'
KEEP TERM: 'Homey' with Cleaned Term: 'homey' and Stem: 'homey'
KEEP TERM: 'Nostalgic' with Cleaned Term: 'nostalgic' and Stem: 'nostalg'
KEEP TERM: 'Tranquil' with Cleaned Term: 'tranquil' and Stem: 'tranquil'
KEEP TERM: 'Comforting' with Cleaned Term: 'comforting' and Stem: 'comfort'
REMOVED Term Found: 'Harvesty' mapped to Cleaned Term: 'harvesty' with Stem: 'harvesti'
KEEP TERM: 'Intense' with Cleaned Term: 'intense' and Stem: 'intens'
KEEP TERM: 'Hopeless' with Cleaned Term: 'hopeless' and Stem: 'hopeless'
KEEP TERM: 'Chaotic' with Cleaned Term: 'chaotic' and Stem: 'chaotic'
KEEP TERM: 'Solemn' with Cleaned Term: 'solemn' and Stem: 'solemn'
KEEP TERM: 'Cerebral' with Cleaned Term: 'cerebral' and Stem: 'cerebr'
KEEP TERM: 'Calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'relaxing' with Cleaned Term: 'relaxing' and Stem: 'relax'
KEEP TERM: 'engrossing' with Cleaned Term: 'engrossing' and Stem: 'engross'
KEEP TERM: 'makes-you-think' with Cleaned Term: 'makes-you-think' and Stem: 'thought-provok'
KEEP TERM: 'adventure' with Cleaned Term: 'adventure' and Stem: 'adventur'
KEEP TERM: 'bright' with Cleaned Term: 'bright' and Stem: 'bright'
KEEP TERM: 'lovely' with Cleaned Term: 'lovely' and Stem: 'love'
KEEP TERM: 'spooky' with Cleaned Term: 'spooky' and Stem: 'spooki'
KEEP TERM: 'elegant' with Cleaned Term: 'elegant' and Stem: 'eleg'
KEEP TERM: 'dreamy' with Cleaned Term: 'dreamy' and Stem: 'dreami'
REMOVED Term Found: 'beautiful' mapped to Cleaned Term: 'beautiful' with Stem: 'beauti'
KEEP TERM: 'sweet' with Cleaned Term: 'sweet' and Stem: 'sweet'
KEEP TERM: 'horror' with Cleaned Term: 'horror' and Stem: 'horror'
KEEP TERM: 'grand' with Cleaned Term: 'grand' and Stem: 'grand'
KEEP TERM: '#Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
REMOVED Term Found: '#Learning' mapped to Cleaned Term: 'learning' with Stem: 'learn'
KEEP TERM: '#Patience' with Cleaned Term: 'patience' and Stem: 'patienc'
REMOVED Term Found: '#Mastery' mapped to Cleaned Term: 'mastery' with Stem: 'masteri'
REMOVED Term Found: '#Skills' mapped to Cleaned Term: 'skills' with Stem: 'skill'
REMOVED Term Found: '#Memory' mapped to Cleaned Term: 'memory' with Stem: 'memori'
KEEP TERM: '#Losing' with Cleaned Term: 'losing' and Stem: 'lose'
KEEP TERM: '#Tactics' with Cleaned Term: 'tactics' and Stem: 'tactic'
KEEP TERM: '#Moving' with Cleaned Term: 'moving' and Stem: 'move'
KEEP TERM: '#Playful' with Cleaned Term: 'playful' and Stem: 'play'
KEEP TERM: 'joy' with Cleaned Term: 'joy' and Stem: 'joy'
REMOVED Term Found: 'whimsical' mapped to Cleaned Term: 'whimsical' with Stem: 'whimsic'
KEEP TERM: 'silly' with Cleaned Term: 'silly' and Stem: 'silli'
KEEP TERM: 'excitement' with Cleaned Term: 'excitement' and Stem: 'excit'
KEEP TERM: 'engrossing' with Cleaned Term: 'engrossing' and Stem: 'engross'
KEEP TERM: 'Atmospheric' with Cleaned Term: 'atmospheric' and Stem: 'atmospher'
KEEP TERM: 'Scary' with Cleaned Term: 'scary' and Stem: 'scari'
KEEP TERM: 'Gut-Wrenching' with Cleaned Term: 'gut-wrenching' and Stem: 'gut-wrench'
KEEP TERM: 'Solemn' with Cleaned Term: 'solemn' and Stem: 'solemn'
KEEP TERM: 'adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'immersive' with Cleaned Term: 'immerse' and Stem: 'immers'
KEEP TERM: 'epic' with Cleaned Term: 'epic' and Stem: 'epic'
KEEP TERM: 'dynamic' with Cleaned Term: 'dynamic' and Stem: 'dynam'
KEEP TERM: 'engaging' with Cleaned Term: 'engaging' and Stem: 'engag'
KEEP TERM: 'expansive' with Cleaned Term: 'expansive' and Stem: 'expans'
KEEP TERM: 'challenging' with Cleaned Term: 'challenging' and Stem: 'challeng'
KEEP TERM: 'mind-bending' with Cleaned Term: 'mind-bending' and Stem: 'mind-bend'
KEEP TERM: 'Hopeful' with Cleaned Term: 'hopeful' and Stem: 'hope'
KEEP TERM: 'Nostalgic' with Cleaned Term: 'nostalgic' and Stem: 'nostalg'
KEEP TERM: 'Adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: '#exasperating' with Cleaned Term: 'exasperating' and Stem: 'exasper'
KEEP TERM: '#frustrating' with Cleaned Term: 'frustrating' and Stem: 'frustrat'
KEEP TERM: '#stressful' with Cleaned Term: 'stressful' and Stem: 'stress'
KEEP TERM: '#exilerating' with Cleaned Term: 'exhilarating' and Stem: 'exhilar'
KEEP TERM: 'silly' with Cleaned Term: 'silly' and Stem: 'silli'
REMOVED Term Found: 'puzzle' mapped to Cleaned Term: 'puzzling' with Stem: 'puzzl'
KEEP TERM: 'nostalgic' with Cleaned Term: 'nostalgic' and Stem: 'nostalg'
KEEP TERM: 'Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Action' with Cleaned Term: 'action' and Stem: 'action'
KEEP TERM: 'Confusing' with Cleaned Term: 'confusing' and Stem: 'confus'
REMOVED Term Found: 'Whimsical' mapped to Cleaned Term: 'whimsical' with Stem: 'whimsic'
KEEP TERM: 'Tactical' with Cleaned Term: 'tactical' and Stem: 'tactic'
KEEP TERM: 'Melancholic' with Cleaned Term: 'melancholic' and Stem: 'melanchol'
KEEP TERM: 'Surreal' with Cleaned Term: 'surreal' and Stem: 'surreal'
KEEP TERM: 'Poetic' with Cleaned Term: 'poetic' and Stem: 'poetic'
KEEP TERM: 'thrilling' with Cleaned Term: 'thrilling' and Stem: 'thrill'
KEEP TERM: 'intriguing' with Cleaned Term: 'intriguing' and Stem: 'intrigu'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'smart' with Cleaned Term: 'smart' and Stem: 'smart'
KEEP TERM: 'thoughtful' with Cleaned Term: 'thoughtful' and Stem: 'thought'
KEEP TERM: 'Calming' with Cleaned Term: 'calming' and Stem: 'calm'
KEEP TERM: 'Stimulating' with Cleaned Term: 'stimulating' and Stem: 'stimul'
KEEP TERM: 'Peaceful' with Cleaned Term: 'peaceful' and Stem: 'peac'
KEEP TERM: 'somber' with Cleaned Term: 'somber' and Stem: 'somber'
REMOVED Term Found: 'tense' mapped to Cleaned Term: 'tense' with Stem: 'tens'
KEEP TERM: 'stressful' with Cleaned Term: 'stressful' and Stem: 'stress'
KEEP TERM: 'dark' with Cleaned Term: 'dark' and Stem: 'dark'
KEEP TERM: 'adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'Combative' with Cleaned Term: 'combative' and Stem: 'comb'
KEEP TERM: 'heroic' with Cleaned Term: 'heroic' and Stem: 'heroic'
KEEP TERM: 'stealthy' with Cleaned Term: 'stealthy' and Stem: 'stealthi'
KEEP TERM: 'adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
REMOVED Term Found: 'violent' mapped to Cleaned Term: 'violent' with Stem: 'violent'
REMOVED Term Found: 'helpful' mapped to Cleaned Term: 'helpful' with Stem: 'help'
REMOVED Term Found: 'medieval' mapped to Cleaned Term: 'medieval' with Stem: 'mediev'
KEEP TERM: 'defensive' with Cleaned Term: 'defensive' and Stem: 'defens'
KEEP TERM: 'offensive' with Cleaned Term: 'offensive' and Stem: 'offens'
KEEP TERM: 'spooky' with Cleaned Term: 'spooky' and Stem: 'spooki'
KEEP TERM: 'celebratory' with Cleaned Term: 'celebratory' and Stem: 'celebratori'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'disorienting' with Cleaned Term: 'disorienting' and Stem: 'disori'
KEEP TERM: 'eclectic' with Cleaned Term: 'eclectic' and Stem: 'eclect'
KEEP TERM: 'fast-paced' with Cleaned Term: 'fast-paced' and Stem: 'fast-pac'
KEEP TERM: 'frustrating' with Cleaned Term: 'frustrating' and Stem: 'frustrat'
KEEP TERM: 'Dark' with Cleaned Term: 'dark' and Stem: 'dark'
KEEP TERM: 'Hopeful' with Cleaned Term: 'hopeful' and Stem: 'hope'
KEEP TERM: 'Nihilistic' with Cleaned Term: 'nihilistic' and Stem: 'nihilist'
KEEP TERM: 'Terrifying' with Cleaned Term: 'terrifying' and Stem: 'terrifi'
KEEP TERM: 'Fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'Triggering' with Cleaned Term: 'triggering' and Stem: 'trigger'
KEEP TERM: 'Sweaty' with Cleaned Term: 'sweaty' and Stem: 'sweati'
REMOVED Term Found: 'Baddass' mapped to Cleaned Term: 'baddest' with Stem: 'baddest'
KEEP TERM: 'Relaxing' with Cleaned Term: 'relaxing' and Stem: 'relax'
KEEP TERM: 'Thought-provoking' with Cleaned Term: 'thought-provoking' and Stem: 'thought-provok'
KEEP TERM: 'Stressful' with Cleaned Term: 'stressful' and Stem: 'stress'
KEEP TERM: 'Frustrating' with Cleaned Term: 'frustrating' and Stem: 'frustrat'
KEEP TERM: 'Calming' with Cleaned Term: 'calming' and Stem: 'calm'
KEEP TERM: 'Bittersweet' with Cleaned Term: 'bittersweet' and Stem: 'bittersweet'
KEEP TERM: 'Dramatic' with Cleaned Term: 'dramatic' and Stem: 'dramat'
KEEP TERM: 'Unpredictable' with Cleaned Term: 'unpredictable' and Stem: 'unpredict'
KEEP TERM: 'Mysterious' with Cleaned Term: 'mysterious' and Stem: 'mysteri'
KEEP TERM: 'Intense' with Cleaned Term: 'intense' and Stem: 'intens'
KEEP TERM: 'Funny' with Cleaned Term: 'funny' and Stem: 'funni'
KEEP TERM: 'Dark' with Cleaned Term: 'dark' and Stem: 'dark'
KEEP TERM: 'Dystopian' with Cleaned Term: 'dystopian' and Stem: 'dystopian'
KEEP TERM: 'Cozy' with Cleaned Term: 'cozy' and Stem: 'cozi'
KEEP TERM: 'Touching' with Cleaned Term: 'touching' and Stem: 'touch'
KEEP TERM: 'Empathetic' with Cleaned Term: 'empathetic' and Stem: 'empathet'
KEEP TERM: 'Hopeful' with Cleaned Term: 'hopeful' and Stem: 'hope'
KEEP TERM: 'Cinematic' with Cleaned Term: 'cinematic' and Stem: 'cinemat'
KEEP TERM: 'Creative' with Cleaned Term: 'creative' and Stem: 'creativ'
KEEP TERM: 'hopeful' with Cleaned Term: 'hopeful' and Stem: 'hope'
KEEP TERM: 'angsty' with Cleaned Term: 'angst' and Stem: 'angsti'
KEEP TERM: 'flirty' with Cleaned Term: 'flirty' and Stem: 'flirti'
KEEP TERM: 'depressing' with Cleaned Term: 'depressing' and Stem: 'depress'
KEEP TERM: 'funny' with Cleaned Term: 'funny' and Stem: 'funni'
REMOVED Term Found: 'tense' mapped to Cleaned Term: 'tense' with Stem: 'tens'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'emotional' with Cleaned Term: 'emotional' and Stem: 'emot'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'light-hearted' with Cleaned Term: 'lighthearted' and Stem: 'lightheart'
KEEP TERM: 'silly' with Cleaned Term: 'silly' and Stem: 'silli'
KEEP TERM: 'futuristic' with Cleaned Term: 'futuristic' and Stem: 'futurist'
KEEP TERM: 'peaceful' with Cleaned Term: 'peaceful' and Stem: 'peac'
KEEP TERM: 'thought-provoking' with Cleaned Term: 'thought-provoking' and Stem: 'thought-provok'
KEEP TERM: 'funny' with Cleaned Term: 'funny' and Stem: 'funni'
KEEP TERM: 'relaxing' with Cleaned Term: 'relaxing' and Stem: 'relax'
KEEP TERM: 'educational' with Cleaned Term: 'educational' and Stem: 'educ'
KEEP TERM: 'intriguing' with Cleaned Term: 'intriguing' and Stem: 'intrigu'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'emotional' with Cleaned Term: 'emotional' and Stem: 'emot'
KEEP TERM: 'nostalgic' with Cleaned Term: 'nostalgic' and Stem: 'nostalg'
KEEP TERM: 'challenging' with Cleaned Term: 'challenging' and Stem: 'challeng'
REMOVED Term Found: 'beautiful' mapped to Cleaned Term: 'beautiful' with Stem: 'beauti'
KEEP TERM: 'bloody' with Cleaned Term: 'bloody' and Stem: 'bloodi'
KEEP TERM: 'gotchic' with Cleaned Term: 'gothic' and Stem: 'gothic'
KEEP TERM: 'horrifying' with Cleaned Term: 'horrifying' and Stem: 'horrifi'
REMOVED Term Found: 'tense' mapped to Cleaned Term: 'tense' with Stem: 'tens'
KEEP TERM: 'fast' with Cleaned Term: 'fast' and Stem: 'fast'
KEEP TERM: 'stressful' with Cleaned Term: 'stressful' and Stem: 'stress'
KEEP TERM: 'uncanny' with Cleaned Term: 'uncanny' and Stem: 'uncanni'
KEEP TERM: 'scary' with Cleaned Term: 'scary' and Stem: 'scari'
KEEP TERM: 'surprising' with Cleaned Term: 'surprising' and Stem: 'surpris'
KEEP TERM: 'engaging' with Cleaned Term: 'engaging' and Stem: 'engag'
KEEP TERM: 'mysterious' with Cleaned Term: 'mysterious' and Stem: 'mysteri'
KEEP TERM: 'thought-provoking' with Cleaned Term: 'thought-provoking' and Stem: 'thought-provok'
KEEP TERM: 'curious' with Cleaned Term: 'curious' and Stem: 'curiou'
REMOVED Term Found: 'whimsical' mapped to Cleaned Term: 'whimsical' with Stem: 'whimsic'
KEEP TERM: 'calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'clever' with Cleaned Term: 'clever' and Stem: 'clever'
KEEP TERM: 'relaxing' with Cleaned Term: 'relaxing' and Stem: 'relax'
KEEP TERM: 'satisfying' with Cleaned Term: 'satisfying' and Stem: 'satisfi'
KEEP TERM: 'lonely' with Cleaned Term: 'lonely' and Stem: 'lone'
KEEP TERM: 'unexpected' with Cleaned Term: 'unexpected' and Stem: 'unexpect'
KEEP TERM: 'cozy' with Cleaned Term: 'cozy' and Stem: 'cozi'
REMOVED Term Found: 'simulation' mapped to Cleaned Term: 'simulation' with Stem: 'simul'
KEEP TERM: 'addictive' with Cleaned Term: 'addictive' and Stem: 'addict'
REMOVED Term Found: 'modable' mapped to Cleaned Term: 'movable' with Stem: 'movabl'
REMOVED Term Found: 'rpg' mapped to Cleaned Term: 'rig' with Stem: 'rig'
KEEP TERM: 'aesthetic' with Cleaned Term: 'aesthetic' and Stem: 'aesthet'
KEEP TERM: 'calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'idyllic' with Cleaned Term: 'idyllic' and Stem: 'idyl'
KEEP TERM: 'adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'strategic' with Cleaned Term: 'strategic' and Stem: 'strateg'
KEEP TERM: 'playful' with Cleaned Term: 'playful' and Stem: 'play'
REMOVED Term Found: 'colorful' mapped to Cleaned Term: 'whimsical' with Stem: 'whimsic'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Shocking' with Cleaned Term: 'shocking' and Stem: 'shock'
KEEP TERM: 'gut-wrenching' with Cleaned Term: 'gut-wrenching' and Stem: 'gut-wrench'
KEEP TERM: 'depressing' with Cleaned Term: 'depressing' and Stem: 'depress'
KEEP TERM: 'heartbreaking' with Cleaned Term: 'heartbreaking' and Stem: 'heartbreak'
KEEP TERM: 'cozy' with Cleaned Term: 'cozy' and Stem: 'cozi'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'reserved' with Cleaned Term: 'reserved' and Stem: 'reserv'
KEEP TERM: 'Thrilling' with Cleaned Term: 'thrilling' and Stem: 'thrill'
KEEP TERM: 'Emotional' with Cleaned Term: 'emotional' and Stem: 'emot'
KEEP TERM: 'Depressing' with Cleaned Term: 'depressing' and Stem: 'depress'
KEEP TERM: 'Gloomy' with Cleaned Term: 'gloomy' and Stem: 'gloomi'
REMOVED Term Found: 'Inevitability' mapped to Cleaned Term: 'inevitability' with Stem: 'inevit'
REMOVED Term Found: 'DnD' mapped to Cleaned Term: 'and' with Stem: 'and'
REMOVED Term Found: 'Depth' mapped to Cleaned Term: 'depth' with Stem: 'depth'
REMOVED Term Found: 'Story' mapped to Cleaned Term: 'story' with Stem: 'stori'
REMOVED Term Found: 'Customization' mapped to Cleaned Term: 'customization' with Stem: 'custom'
KEEP TERM: 'Peaceful' with Cleaned Term: 'peaceful' and Stem: 'peac'
KEEP TERM: 'Calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'Chill' with Cleaned Term: 'chill' and Stem: 'chill'
KEEP TERM: 'Nostalgic' with Cleaned Term: 'nostalgic' and Stem: 'nostalg'
KEEP TERM: 'Comforting' with Cleaned Term: 'comforting' and Stem: 'comfort'
KEEP TERM: 'Aesthetic' with Cleaned Term: 'aesthetic' and Stem: 'aesthet'
KEEP TERM: 'Secure' with Cleaned Term: 'secure' and Stem: 'secur'
KEEP TERM: 'Happy' with Cleaned Term: 'happy' and Stem: 'happi'
KEEP TERM: 'At ease' with Cleaned Term: 'tease' and Stem: 'relax'
KEEP TERM: 'Calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'Spooked' with Cleaned Term: 'spooked' and Stem: 'spook'
KEEP TERM: 'Scared' with Cleaned Term: 'scared' and Stem: 'scare'
KEEP TERM: 'Unknowing' with Cleaned Term: 'unknowing' and Stem: 'unknow'
KEEP TERM: 'Entertaining' with Cleaned Term: 'entertaining' and Stem: 'entertain'
KEEP TERM: 'Adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'Action-Packed' with Cleaned Term: 'action-packed' and Stem: 'action-pack'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'gut-wrenching' with Cleaned Term: 'gut-wrenching' and Stem: 'gut-wrench'
KEEP TERM: 'sad' with Cleaned Term: 'sad' and Stem: 'sad'
KEEP TERM: 'thrilling' with Cleaned Term: 'thrilling' and Stem: 'thrill'
KEEP TERM: 'Frusterating' with Cleaned Term: 'frustrating' and Stem: 'frustrat'
KEEP TERM: 'Happy' with Cleaned Term: 'happy' and Stem: 'happi'
KEEP TERM: 'Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Focused' with Cleaned Term: 'focused' and Stem: 'focus'
KEEP TERM: 'Fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'Tired' with Cleaned Term: 'tired' and Stem: 'tire'
KEEP TERM: 'Annoyed' with Cleaned Term: 'annoyed' and Stem: 'annoy'
KEEP TERM: 'Cool' with Cleaned Term: 'cool' and Stem: 'cool'
REMOVED Term Found: 'Friendly' mapped to Cleaned Term: 'friendly' with Stem: 'friendli'
KEEP TERM: 'Angering' with Cleaned Term: 'angering' and Stem: 'anger'
KEEP TERM: 'Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Curiosity' with Cleaned Term: 'curiosity' and Stem: 'curiou'
KEEP TERM: 'Upbeat' with Cleaned Term: 'upbeat' and Stem: 'upbeat'
KEEP TERM: 'Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Energetic' with Cleaned Term: 'energetic' and Stem: 'energet'
KEEP TERM: 'Competitive' with Cleaned Term: 'competitive' and Stem: 'competit'
KEEP TERM: 'Curious' with Cleaned Term: 'curious' and Stem: 'curiou'
REMOVED Term Found: 'Tense' mapped to Cleaned Term: 'tense' with Stem: 'tens'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
REMOVED Term Found: 'cooperative' mapped to Cleaned Term: 'cooperative' with Stem: 'cooper'
KEEP TERM: 'adventure' with Cleaned Term: 'adventure' and Stem: 'adventur'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'despair' with Cleaned Term: 'despair' and Stem: 'despair'
KEEP TERM: 'exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'engrossing' with Cleaned Term: 'engrossing' and Stem: 'engross'
REMOVED Term Found: 'tense' mapped to Cleaned Term: 'tense' with Stem: 'tens'
KEEP TERM: 'lude' with Cleaned Term: 'dude' and Stem: 'lewd'
KEEP TERM: 'funny' with Cleaned Term: 'funny' and Stem: 'funni'
KEEP TERM: 'Heartwrenching' with Cleaned Term: 'heartwrenching' and Stem: 'heartwrench'
KEEP TERM: 'Atmospheric' with Cleaned Term: 'atmospheric' and Stem: 'atmospher'
KEEP TERM: 'Compelling' with Cleaned Term: 'compelling' and Stem: 'compel'
KEEP TERM: 'Mysterious' with Cleaned Term: 'mysterious' and Stem: 'mysteri'
KEEP TERM: 'Foreboding' with Cleaned Term: 'foreboding' and Stem: 'forebod'
KEEP TERM: 'Rich' with Cleaned Term: 'rich' and Stem: 'rich'
KEEP TERM: 'Harrowing' with Cleaned Term: 'harrowing' and Stem: 'harrow'
KEEP TERM: 'Exciting' with Cleaned Term: 'exciting' and Stem: 'excit'
KEEP TERM: 'Charming' with Cleaned Term: 'charming' and Stem: 'charm'
KEEP TERM: 'Difficult' with Cleaned Term: 'difficult' and Stem: 'difficult'
KEEP TERM: 'Challenging' with Cleaned Term: 'challenging' and Stem: 'challeng'
KEEP TERM: 'Engaging' with Cleaned Term: 'engaging' and Stem: 'engag'
KEEP TERM: 'Smart' with Cleaned Term: 'smart' and Stem: 'smart'
REMOVED Term Found: 'Whole' mapped to Cleaned Term: 'whole' with Stem: 'whole'
KEEP TERM: 'Adventurous' with Cleaned Term: 'adventurous' and Stem: 'adventur'
KEEP TERM: 'Calm' with Cleaned Term: 'calm' and Stem: 'calm'
KEEP TERM: 'Cozy' with Cleaned Term: 'cozy' and Stem: 'cozi'
REMOVED Term Found: 'Constructive' mapped to Cleaned Term: 'constructive' with Stem: 'construct'
REMOVED Term Found: 'Open' mapped to Cleaned Term: 'open' with Stem: 'open'
KEEP TERM: 'Repetitive' with Cleaned Term: 'repetitive' and Stem: 'repetit'
KEEP TERM: 'relaxing' with Cleaned Term: 'relaxing' and Stem: 'relax'
KEEP TERM: 'fun' with Cleaned Term: 'fun' and Stem: 'fun'
KEEP TERM: 'stressful' with Cleaned Term: 'stressful' and Stem: 'stress'
KEEP TERM: 'calm' with Cleaned Term: 'calm' and Stem: 'calm'

In [89]:
temp_df.head(10)

,metadata.ResponseId,metadata.Finished,metadata.Progress,metadata.TermTrack,metadata.QuestionId,QX_X.UserProvidedMoodTerm,QX_X.CleanedMoodTerm,QX_X.CleanedTermStem,QX_X.RemovedTermFlag,QX_X.UserCategoryMapping,QX.MultipleCategoryTerm,QX#1_X.MultipleCategoryMapping,QX#2_X_1.UserProvidedCategory,QX#2_X_1.CleanedCategory
0,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_1,Cozy,cozy,cozi,False,Peaceful,False,None,None,None
1,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_2,Peaceful,peaceful,peac,False,Peaceful,False,None,None,None
2,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_3,Homey,homey,homey,False,Light-hearted,False,None,None,None
3,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_4,Nostalgic,nostalgic,nostalg,False,Peaceful,True,"[Light-hearted, Peaceful]",None,None
4,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_5,Tranquil,tranquil,tranquil,False,Peaceful,False,None,None,None
5,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_6,Comforting,comforting,comfort,False,Peaceful,False,None,None,None
6,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_7,Harvesty,harvesty,harvesti,True,No match,False,None,None,None
7,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_8,Intense,intense,intens,False,Intense,False,None,None,None
8,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_9,Hopeless,hopeless,hopeless,False,Dark,False,None,None,None
9,R_1M0P04gYkqgIfoB,True,100,Recent,Q2_10,Chaotic,chaotic,chaotic,False,Dark,True,"[Dark, Intense]",None,None

In [90]:
temp_df.to_csv('Data/Outbound/all_terms_cleaned_stemmed.csv', index=False, header=True)
temp_df.to_excel('Data/Outbound/all_terms_cleaned_stemmed.xlsx', index=False, header=True)

## General Testing

In [91]:
temp_df[temp_df['QX_X.RemovedTermFlag'] == True].shape

(171, 14)

In [92]:
temp_df[temp_df['QX_X.RemovedTermFlag'] == False].shape

(1328, 14)