# Survey Data Analysis
A preliminary data survey to profile survey results

This notebook was written on May 19th, 2025 to address recruitment issues

# Report Summary

## Completion

As of the time of this investigation, there have been 109 survey submissions. Of those submissions, 65 were 100% complete.

| Progress       | Count |
|----------------|-------|
| 100            | 65    |
| 57             | 2     |
| 33             | 14    |
| 29             | 5     |
| 24             | 1     |
| 14             | 3     |
| 10             | 19    |

## Terms Provided
### Recent
Respondents on average provided 4.72 terms. Across respondents, 515 terms (non-unique) were provided.
### Favorite
Respondents on average provided 3.64 terms. Across respondents, 397 terms (non-unique) were provided.
### Avoid
Respondents on average provided 2.55 terms. Across respondents, 278 terms (non-unique) were provided.

## Categories Assigned
### Recent Term Categories
| Category         | Count |
|------------------|-------|
| NAN              | 584   |
| Peaceful         | 51    |
| Light-hearted    | 41    |
| No match         | 39    |
| Intense          | 69    |
| Dark             | 24    |
| Imaginative      | 61    |
| Adventurous      | 67    |
| Romantic         | 4     |
| Mysterious       | 33    |
| Cute             | 14    |
| Horror           | 9     |
| Humorous         | 21    |
| Sad              | 16    |
| Solitary         | 13    |
| Quirky           | 16    |
| Aggressive       | 20    |
| Sensual          | 6     |
| Sarcastic        | 2     |

### Favorite Term Categories
| Category         | Count |
|------------------|-------|
| NAN              | 693   |
| Peaceful         | 33    |
| Cute             | 12    |
| Light-hearted    | 33    |
| No match         | 34    |
| Imaginative      | 50    |
| Adventurous      | 57    |
| Mysterious       | 23    |
| Romantic         | 7     |
| Horror           | 6     |
| Humorous         | 20    |
| Intense          | 54    |
| Sad              | 13    |
| Dark             | 19    |
| Solitary         | 2     |
| Aggressive       | 14    |
| Quirky           | 14    |
| Sensual          | 3     |
| Sarcastic        | 3     |

### Avoid Term Categories
| Category         | Count |
|------------------|-------|
| NAN              | 804   |
| Intense          | 32    |
| Horror           | 38    |
| Dark             | 25    |
| Sensual          | 14    |
| Sad              | 24    |
| Mysterious       | 2     |
| Aggressive       | 47    |
| No match         | 63    |
| Adventurous      | 3     |
| Sarcastic        | 3     |
| Quirky           | 4     |
| Solitary         | 16    |
| Light-hearted    | 1     |
| Peaceful         | 8     |
| Imaginative      | 2     |
| Romantic         | 2     |
| Cute             | 1     |
| Humorous         | 1     |

## Multi-Category Terms
### Recent
34 respondents said *none* of their terms could be represented by multiple categories.

### Favorite
38 respondents said *none* of their terms could be represented by multiple categories.

### Avoid
44 respondents said *none* of their terms could be represented by multiple categories.

## Age Distribution
| Age Group       | Count |
|-----------------|-------|
| 26-33           | 34    |
| 18-25           | 15    |
| 34-41           | 8     |
| 42-49           | 4     |
| 50-57           | 3     |
| 58-65           | 1     |

## Gender Distribution
| Gender Group       | Count |
|-----------------|-------|
| Male            | 28    |
| Female          | 26    |
| Gender variant/non-conforming | 8     |
| Prefer not to answer | 2     |
| Prefer to self-describe | 1     |

## Imports

In [1]:
#imports
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Survey_Data_05_27_2025.csv')
# df = pd.read_csv('Survey_Data_05_19_2025.csv')
df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please tell us about yourself. What is your age?,How do you identify your gender? - Selected Ch...,How do you identify your gender? - Prefer to s...,Do you have an occupation related to video games?,What is your job? - Selected Choice,What is your job? - None of the above. My job ...
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID17#2_xx7_1""}","{""ImportId"":""QID17#2_xx8_1""}","{""ImportId"":""QID17#2_xx9_1""}","{""ImportId"":""QID17#2_xx10_1""}","{""ImportId"":""QID18""}","{""ImportId"":""QID19""}","{""ImportId"":""QID19_4_TEXT""}","{""ImportId"":""QID20""}","{""ImportId"":""QID21""}","{""ImportId"":""QID21_5_TEXT""}"
2,2025-04-30 11:21:17,2025-04-30 11:41:55,IP Address,184.58.198.91,100,1238,True,2025-04-30 11:41:56,R_1M0P04gYkqgIfoB,NaN,...,NaN,NaN,NaN,NaN,26-33,Female,NaN,No,NaN,NaN

In [3]:
question_df = df[df['StartDate']== 'Start Date']
question_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please select all the categories that represen...,Please tell us about yourself. What is your age?,How do you identify your gender? - Selected Ch...,How do you identify your gender? - Prefer to s...,Do you have an occupation related to video games?,What is your job? - Selected Choice,What is your job? - None of the above. My job ...

In [4]:
metadata_df = df[df['Status']== '{"ImportId":"status"}']
metadata_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID17#2_xx7_1""}","{""ImportId"":""QID17#2_xx8_1""}","{""ImportId"":""QID17#2_xx9_1""}","{""ImportId"":""QID17#2_xx10_1""}","{""ImportId"":""QID18""}","{""ImportId"":""QID19""}","{""ImportId"":""QID19_4_TEXT""}","{""ImportId"":""QID20""}","{""ImportId"":""QID21""}","{""ImportId"":""QID21_5_TEXT""}"

In [5]:
response_df = df[(df['StartDate']!= 'Start Date') & (df['Status']!= '{"ImportId":"status"}')].reset_index(drop=True)
response_df.head(3)

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q13#2_8_1,Q13#2_9_1,Q13#2_10_1,Q13#2_11_1,Q14,Q15,Q15_4_TEXT,Q16,Q17,Q17_5_TEXT
0,2025-04-30 11:21:17,2025-04-30 11:41:55,IP Address,184.58.198.91,100,1238,True,2025-04-30 11:41:56,R_1M0P04gYkqgIfoB,NaN,...,NaN,NaN,NaN,NaN,26-33,Female,NaN,No,NaN,NaN
1,2025-04-30 12:34:03,2025-04-30 12:39:20,IP Address,68.55.41.237,100,317,True,2025-04-30 12:39:21,R_6hA6yOKSGzPDXlp,NaN,...,NaN,NaN,NaN,NaN,50-57,Male,NaN,No,NaN,NaN
2,2025-04-30 14:30:54,2025-04-30 14:39:56,IP Address,184.58.199.136,100,541,True,2025-04-30 14:39:57,R_34jUAPsFHDjPeyy,NaN,...,NaN,NaN,NaN,NaN,50-57,Female,NaN,No,NaN,NaN

## Completion Review

In [6]:
response_df.shape

(158, 153)

In [7]:
response_df['Progress'].value_counts()

100    80
10     38
33     20
14      8
29      5
57      4
24      3
Name: Progress, dtype: int64

Of the 109 responses received for the survey, only 65 have completed the full survey.

## Terms

In [8]:
recent_q = ['Q2_1','Q2_2','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7','Q2_8','Q2_9','Q2_10']
recent_categories = ['Q3_1','Q3_2','Q3_3','Q3_4','Q3_5','Q3_6','Q3_7','Q3_8','Q3_9','Q3_10']
multi_recent_q = ['Q4']
fav_q = ['Q6_1','Q6_2','Q6_3','Q6_4','Q6_5','Q6_6','Q6_7','Q6_8','Q6_9','Q6_10']
fav_categories = ['Q7_1','Q7_2','Q7_3','Q7_4','Q7_5','Q7_6','Q7_7','Q7_8','Q7_9','Q7_10']
multi_fav_q = ['Q8']
avoid_q = ['Q10_1','Q10_2','Q10_3','Q10_4','Q10_5','Q10_6','Q10_7','Q10_8','Q10_9','Q10_10']
avoid_categories = ['Q11_1','Q11_2','Q11_3','Q11_4','Q11_5','Q11_6','Q11_7','Q11_8','Q11_9','Q11_10']
multi_avoid_q = ['Q12']
age_q = ['Q14']
gender_q = ['Q15']

### Recent Game Terms

In [9]:
# recent game terms
recent_terms_df = response_df[recent_q].copy()
recent_terms_df.head(3)

,Q2_1,Q2_2,Q2_3,Q2_4,Q2_5,Q2_6,Q2_7,Q2_8,Q2_9,Q2_10
0,Cozy,Peaceful,Homey,Nostalgic,Tranquil,Comforting,Harvesty,Intense,Hopeless,Chaotic
1,Solemn,Cerebral,Calm,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,relaxing,engrossing,makes-you-think,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
total_recent_terms = pd.DataFrame(recent_terms_df[recent_q].count(axis=1))
total_recent_terms.rename(columns={0:'Total_Recent_Terms'}, inplace=True)
total_recent_terms.head(3)

   Total_Recent_Terms
0                  10
1                   3
2                   3

In [11]:
total_recent_terms.describe()

       Total_Recent_Terms
count          158.000000
mean             4.278481
std              3.496811
min              0.000000
25%              0.000000
50%              4.000000
75%              6.000000
max             10.000000

In [12]:
total_recent_terms['Total_Recent_Terms'].sum()

676

### Favorite Game Terms

In [13]:
favorite_terms_df = response_df[fav_q].copy()
favorite_terms_df.head(3)

,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,Q6_10
0,Cozy,Cute,Simple,Warm,Peaceful,Nostalgic,Satisfied,Fulfilled,Connected,Immersive
1,Calm,Cerebral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,creative,fun,relaxing,imaginative,explorative,NaN,NaN,NaN,NaN,NaN

In [14]:
total_favorite_terms = pd.DataFrame(favorite_terms_df[fav_q].count(axis=1))
total_favorite_terms.rename(columns={0:'Total_Favorite_Terms'}, inplace=True)
total_favorite_terms.head(3)

   Total_Favorite_Terms
0                    10
1                     2
2                     5

In [15]:
total_favorite_terms.describe()

       Total_Favorite_Terms
count            158.000000
mean               3.113924
std                3.553010
min                0.000000
25%                0.000000
50%                1.500000
75%                6.000000
max               10.000000

In [16]:
total_favorite_terms['Total_Favorite_Terms'].sum()

492

### Avoid Game Terms

In [17]:
#avoid game terms
avoid_terms_df = response_df[avoid_q].copy()
avoid_terms_df.head(3)

,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_10
0,Intense,Anxious,Frustrated,Tormented,Tense,Haunting,Stressful,Overwhelming,Violent,Sextual
1,Depressing,Frustrating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,depressing,sad,gross,horror,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
total_avoid_terms = pd.DataFrame(avoid_terms_df[avoid_q].count(axis=1))
total_avoid_terms.rename(columns={0:'Total_Avoid_Terms'}, inplace=True)
total_avoid_terms.head(3)

   Total_Avoid_Terms
0                 10
1                  2
2                  4

In [19]:
total_avoid_terms.describe()

       Total_Avoid_Terms
count         158.000000
mean            2.037975
std             2.855068
min             0.000000
25%             0.000000
50%             0.000000
75%             4.000000
max            10.000000

In [20]:
total_avoid_terms['Total_Avoid_Terms'].sum()

322

## Categories

### Recent Categories Assigned

In [21]:
recent_categories_df = response_df[recent_categories].copy()
recent_categories_df.head(3)

,Q3_1,Q3_2,Q3_3,Q3_4,Q3_5,Q3_6,Q3_7,Q3_8,Q3_9,Q3_10
0,Peaceful,Peaceful,Light-hearted,Peaceful,Peaceful,Peaceful,No match,Intense,Dark,Dark
1,Peaceful,Imaginative,Peaceful,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Peaceful,No match,Imaginative,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
recent_count = {'NAN':0}

for idx, row in recent_categories_df.iterrows():
    for col in recent_categories:
        if pd.isna(row[col]):
            recent_count['NAN'] += 1
        else:
            if row[col] not in recent_count:
                recent_count[row[col]] = 1
            else:
                recent_count[row[col]] += 1

In [23]:
recent_count

{'NAN': 931,
 'Peaceful': 63,
 'Light-hearted': 48,
 'No match': 48,
 'Intense': 94,
 'Dark ': 35,
 'Imaginative': 68,
 'Adventurous  ': 88,
 'Romantic': 7,
 'Mysterious': 40,
 'Cute  ': 19,
 'Horror ': 15,
 'Humorous ': 24,
 'Sad': 24,
 'Solitary': 16,
 'Quirky': 19,
 'Aggressive ': 32,
 'Sensual': 7,
 'Sarcastic': 2}

In [24]:
# Convert recent_count dictionary to a markdown table
recent_count_table = "| Category         | Count |\n|------------------|-------|\n"
for category, count in recent_count.items():
    recent_count_table += f"| {category:<16} | {count:<5} |\n"

print(recent_count_table)

| Category         | Count |
|------------------|-------|
| NAN              | 931   |
| Peaceful         | 63    |
| Light-hearted    | 48    |
| No match         | 48    |
| Intense          | 94    |
| Dark             | 35    |
| Imaginative      | 68    |
| Adventurous      | 88    |
| Romantic         | 7     |
| Mysterious       | 40    |
| Cute             | 19    |
| Horror           | 15    |
| Humorous         | 24    |
| Sad              | 24    |
| Solitary         | 16    |
| Quirky           | 19    |
| Aggressive       | 32    |
| Sensual          | 7     |
| Sarcastic        | 2     |

### Fave Categories Assigned

In [25]:
fav_categories_df = response_df[fav_categories].copy()
fav_categories_df.head(3)

,Q7_1,Q7_2,Q7_3,Q7_4,Q7_5,Q7_6,Q7_7,Q7_8,Q7_9,Q7_10
0,Peaceful,Cute,Light-hearted,Peaceful,Peaceful,Peaceful,No match,No match,No match,No match
1,Peaceful,Imaginative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Imaginative,Light-hearted,Peaceful,Imaginative,Adventurous,NaN,NaN,NaN,NaN,NaN

In [26]:
fav_count = {'NAN':0}

for idx, row in fav_categories_df.iterrows():
    for col in fav_categories:
        if pd.isna(row[col]):
            fav_count['NAN'] += 1
        else:
            if row[col] not in fav_count:
                fav_count[row[col]] = 1
            else:
                fav_count[row[col]] += 1

In [27]:
fav_count

{'NAN': 1088,
 'Peaceful': 38,
 'Cute  ': 12,
 'Light-hearted': 39,
 'No match': 40,
 'Imaginative': 59,
 'Adventurous  ': 70,
 'Mysterious': 25,
 'Romantic': 11,
 'Horror ': 8,
 'Humorous ': 25,
 'Intense': 64,
 'Sad': 25,
 'Dark ': 26,
 'Solitary': 2,
 'Aggressive ': 25,
 'Quirky': 16,
 'Sensual': 3,
 'Sarcastic': 4}

In [28]:
# Convert fav_count dictionary to a markdown table
fav_count_table = "| Category         | Count |\n|------------------|-------|\n"
for category, count in fav_count.items():
    fav_count_table += f"| {category:<16} | {count:<5} |\n"

print(fav_count_table)

| Category         | Count |
|------------------|-------|
| NAN              | 1088  |
| Peaceful         | 38    |
| Cute             | 12    |
| Light-hearted    | 39    |
| No match         | 40    |
| Imaginative      | 59    |
| Adventurous      | 70    |
| Mysterious       | 25    |
| Romantic         | 11    |
| Horror           | 8     |
| Humorous         | 25    |
| Intense          | 64    |
| Sad              | 25    |
| Dark             | 26    |
| Solitary         | 2     |
| Aggressive       | 25    |
| Quirky           | 16    |
| Sensual          | 3     |
| Sarcastic        | 4     |

### Avoid Categories Assigned

In [29]:
avoid_categories_df = response_df[avoid_categories].copy()
avoid_categories_df.head(3)

,Q11_1,Q11_2,Q11_3,Q11_4,Q11_5,Q11_6,Q11_7,Q11_8,Q11_9,Q11_10
0,Intense,Intense,Intense,Horror,Intense,Horror,Intense,Intense,Dark,Sensual
1,Sad,Mysterious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sad,Sad,Dark,Horror,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
avoid_count = {'NAN':0}

for idx, row in avoid_categories_df.iterrows():
    for col in avoid_categories:
        if pd.isna(row[col]):
            avoid_count['NAN'] += 1
        else:
            if row[col] not in avoid_count:
                avoid_count[row[col]] = 1
            else:
                avoid_count[row[col]] += 1

In [31]:
avoid_count

{'NAN': 1250,
 'Intense': 32,
 'Horror ': 50,
 'Dark ': 25,
 'Sensual': 14,
 'Sad': 25,
 'Mysterious': 2,
 'Aggressive ': 50,
 'No match': 82,
 'Adventurous  ': 3,
 'Sarcastic': 3,
 'Quirky': 8,
 'Solitary': 16,
 'Light-hearted': 1,
 'Peaceful': 8,
 'Imaginative': 3,
 'Romantic': 5,
 'Cute  ': 2,
 'Humorous ': 1}

In [32]:
# Convert avoid_count dictionary to a markdown table
avoid_count_table = "| Category         | Count |\n|------------------|-------|\n"
for category, count in avoid_count.items():
    avoid_count_table += f"| {category:<16} | {count:<5} |\n"

print(avoid_count_table)

| Category         | Count |
|------------------|-------|
| NAN              | 1250  |
| Intense          | 32    |
| Horror           | 50    |
| Dark             | 25    |
| Sensual          | 14    |
| Sad              | 25    |
| Mysterious       | 2     |
| Aggressive       | 50    |
| No match         | 82    |
| Adventurous      | 3     |
| Sarcastic        | 3     |
| Quirky           | 8     |
| Solitary         | 16    |
| Light-hearted    | 1     |
| Peaceful         | 8     |
| Imaginative      | 3     |
| Romantic         | 5     |
| Cute             | 2     |
| Humorous         | 1     |

## Multi-Category

### Multi-Recent Frequency

In [33]:
multi_recent_freq = response_df[multi_recent_q].copy()
multi_recent_freq.head(3)

                         Q4
0  Mood Term 4,Mood Term 10
1                        No
2                        No

In [34]:
multi_recent_freq[multi_recent_freq['Q4']=='No'].shape[0]

45

### Multi-Favorite Frequency

In [35]:
multi_fav_freq = response_df[multi_fav_q].copy()
multi_fav_freq.head(3)

            Q8
0  Mood Term 6
1           No
2           No

In [36]:
multi_fav_freq[multi_fav_freq['Q8']=='No'].shape[0]

48

### Multi-Avoid Frequency

In [37]:
multi_avoid_freq = response_df[multi_avoid_q].copy()
multi_avoid_freq.head(3)

                       Q12
0  Mood Term 4,Mood Term 9
1                       No
2                       No

In [38]:
multi_avoid_freq[multi_avoid_freq['Q12']=='No'].shape[0]

58

## Age Distribution

In [39]:
age_df = response_df[age_q].copy()
age_df.head(5)

     Q14
0  26-33
1  50-57
2  50-57
3  26-33
4  34-41

In [40]:
age_df['Q14'].value_counts()

26-33    38
18-25    21
34-41    12
50-57     4
42-49     4
58-65     1
Name: Q14, dtype: int64

In [41]:
# Convert age distribution into a markdown table
age_distribution = age_df['Q14'].value_counts()
age_table = "| Age Group       | Count |\n|-----------------|-------|\n"
for age_group, count in age_distribution.items():
    age_table += f"| {age_group:<15} | {count:<5} |\n"

print(age_table)

| Age Group       | Count |
|-----------------|-------|
| 26-33           | 38    |
| 18-25           | 21    |
| 34-41           | 12    |
| 50-57           | 4     |
| 42-49           | 4     |
| 58-65           | 1     |

## Gender Distribution

In [42]:
gender_df = response_df[gender_q].copy()
gender_df.head(5)

                             Q15
0                         Female
1                           Male
2                         Female
3  Gender variant/non-conforming
4                           Male

In [43]:
gender_df['Q15'].value_counts()

Male                             42
Female                           27
Gender variant/non-conforming     8
Prefer not to answer              2
Prefer to self-describe           1
Name: Q15, dtype: int64

In [44]:
# Convert age distribution into a markdown table
gender_distribution = gender_df['Q15'].value_counts()
gender_table = "| Gender Group       | Count |\n|-----------------|-------|\n"
for gender_group, count in gender_distribution.items():
    gender_table += f"| {gender_group:<15} | {count:<5} |\n"

print(gender_table)

| Gender Group       | Count |
|-----------------|-------|
| Male            | 42    |
| Female          | 27    |
| Gender variant/non-conforming | 8     |
| Prefer not to answer | 2     |
| Prefer to self-describe | 1     |